ALTER TABLE ACCOUNT
    ADD CONSTRAINT CLIENT_ID
    FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(CLIENT_ID);

ALTER TABLE TRANSACTION
    ADD CONSTRAINT ACCOUNT_ID
    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);